### ISSUE TITLE
Rails 4.0.0 support

### ISSUE THREAD

**Issue by jeffl8n** [owenthereal/devise_uid#1]
Can you update the gemspec to allow for Rails 4.0.0 support?

Line 22:
Remove:
 gem.add_dependency("railties", "~> 3.0")
Add:  
 gem.add_dependency("railties", ">= 3.0")

**Comment by owenthereal** [comment]
Fixed in b59475d46390e6a80e9032e2173dda993c34ae75.

**Comment by pion139** [comment]
same issue now with rails 5.1    
 devise_uid was resolved to 0.1.1, which depends on
      railties (>= 3.0)
