### ISSUE TITLE
Migration name does not end with ".rb"

### ISSUE THREAD

**Issue by thenadz** [owenthereal/devise_uid#4]
Using version `0.1.0`, the generated migration name is missing the file extensions.

This should just require fixing `copy_devise_migration`:
`migration_template "migration.rb", "db/migrate/devise_uid_add_to_#{table_name}.rb"`

**Comment by johncjensen** [comment]
+1 same issue...

**Comment by owenthereal** [comment]
Thanks for reporting the issue. Please see https://github.com/jingweno/devise_uid/pull/5

**Comment by owenthereal** [comment]
Released https://github.com/jingweno/devise_uid/releases/tag/v0.1.1. Please update and let me know if it works or not.
